# Generated by Django 5.2.6 on 2025-09-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Check to display this staff member on the homepage.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
