# Generated by Django 5.2.6 on 2025-09-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='staff',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
