name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4

    # Python setup
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Node.js setup
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    # Install Python dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Tailwind dependencies
    - name: Install Tailwind dependencies
      run: |
        cd theme/static_src
        npm install

    # Build Tailwind CSS
    - name: Build Tailwind CSS
      run: |
        cd theme/static_src
        npm run build

    # Apply migrations
    - name: Apply migrations
      run: python manage.py migrate